/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Card = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Card model module.
   * @module model/Card
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Card</code>.
   * @alias module:model/Card
   * @class
   * @param fkTipoTarjeta {String} Loyalty card type ID
   * @param descripcionTipoTarjeta {String} Loyalty card type name
   * @param valorPunto {String} Value of each point earned
   */
  var exports = function(fkTipoTarjeta, descripcionTipoTarjeta, valorPunto) {
    var _this = this;

    _this['fk_TipoTarjeta'] = fkTipoTarjeta;
    _this['DescripcionTipoTarjeta'] = descripcionTipoTarjeta;
    _this['ValorPunto'] = valorPunto;
  };

  /**
   * Constructs a <code>Card</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Card} obj Optional instance to populate.
   * @return {module:model/Card} The populated <code>Card</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fk_TipoTarjeta')) {
        obj['fk_TipoTarjeta'] = ApiClient.convertToType(data['fk_TipoTarjeta'], 'String');
      }
      if (data.hasOwnProperty('DescripcionTipoTarjeta')) {
        obj['DescripcionTipoTarjeta'] = ApiClient.convertToType(data['DescripcionTipoTarjeta'], 'String');
      }
      if (data.hasOwnProperty('ValorPunto')) {
        obj['ValorPunto'] = ApiClient.convertToType(data['ValorPunto'], 'String');
      }
    }
    return obj;
  }

  /**
   * Loyalty card type ID
   * @member {String} fk_TipoTarjeta
   */
  exports.prototype['fk_TipoTarjeta'] = undefined;
  /**
   * Loyalty card type name
   * @member {String} DescripcionTipoTarjeta
   */
  exports.prototype['DescripcionTipoTarjeta'] = undefined;
  /**
   * Value of each point earned
   * @member {String} ValorPunto
   */
  exports.prototype['ValorPunto'] = undefined;



  return exports;
}));


