/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.CategoryRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CategoryRequest model module.
   * @module model/CategoryRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>CategoryRequest</code>.
   * @alias module:model/CategoryRequest
   * @class
   * @param pkRubro {String} ID of the category
   * @param idClub {String} 
   * @param idTipoTarjeta {String} Card type ID
   * @param latitud {String} Latitude for the user's location (apparently not used)
   * @param longitud {String} Longitude for the user's location (apparently not used)
   */
  var exports = function(pkRubro, idClub, idTipoTarjeta, latitud, longitud) {
    var _this = this;

    _this['pk_Rubro'] = pkRubro;
    _this['IdClub'] = idClub;
    _this['IdTipoTarjeta'] = idTipoTarjeta;
    _this['Latitud'] = latitud;
    _this['Longitud'] = longitud;
  };

  /**
   * Constructs a <code>CategoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CategoryRequest} obj Optional instance to populate.
   * @return {module:model/CategoryRequest} The populated <code>CategoryRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pk_Rubro')) {
        obj['pk_Rubro'] = ApiClient.convertToType(data['pk_Rubro'], 'String');
      }
      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
      if (data.hasOwnProperty('IdTipoTarjeta')) {
        obj['IdTipoTarjeta'] = ApiClient.convertToType(data['IdTipoTarjeta'], 'String');
      }
      if (data.hasOwnProperty('Latitud')) {
        obj['Latitud'] = ApiClient.convertToType(data['Latitud'], 'String');
      }
      if (data.hasOwnProperty('Longitud')) {
        obj['Longitud'] = ApiClient.convertToType(data['Longitud'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of the category
   * @member {String} pk_Rubro
   */
  exports.prototype['pk_Rubro'] = undefined;
  /**
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;
  /**
   * Card type ID
   * @member {String} IdTipoTarjeta
   */
  exports.prototype['IdTipoTarjeta'] = undefined;
  /**
   * Latitude for the user's location (apparently not used)
   * @member {String} Latitud
   */
  exports.prototype['Latitud'] = undefined;
  /**
   * Longitude for the user's location (apparently not used)
   * @member {String} Longitud
   */
  exports.prototype['Longitud'] = undefined;



  return exports;
}));


