/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeInformationResponsev2message'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangeInformationResponsev2message'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.ChangeInformationResponsev2 = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.ChangeInformationResponsev2message);
  }
}(this, function(ApiClient, ChangeInformationResponsev2message) {
  'use strict';




  /**
   * The ChangeInformationResponsev2 model module.
   * @module model/ChangeInformationResponsev2
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>ChangeInformationResponsev2</code>.
   * @alias module:model/ChangeInformationResponsev2
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ChangeInformationResponsev2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangeInformationResponsev2} obj Optional instance to populate.
   * @return {module:model/ChangeInformationResponsev2} The populated <code>ChangeInformationResponsev2</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('estado')) {
        obj['estado'] = ApiClient.convertToType(data['estado'], 'String');
      }
      if (data.hasOwnProperty('mensaje')) {
        obj['mensaje'] = ChangeInformationResponsev2message.constructFromObject(data['mensaje']);
      }
    }
    return obj;
  }

  /**
   * value \"1\" if the information was changed successfully.
   * @member {String} estado
   */
  exports.prototype['estado'] = undefined;
  /**
   * @member {module:model/ChangeInformationResponsev2message} mensaje
   */
  exports.prototype['mensaje'] = undefined;



  return exports;
}));


