/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.ChangePassword = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ChangePassword model module.
   * @module model/ChangePassword
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>ChangePassword</code>.
   * @alias module:model/ChangePassword
   * @class
   * @param mIdSocio {String} User's ID
   * @param mIdClub {String} clubID
   * @param mClaveVieja {String} Previous Password
   * @param mClaveNueva {String} New Password
   */
  var exports = function(mIdSocio, mIdClub, mClaveVieja, mClaveNueva) {
    var _this = this;

    _this['mIdSocio'] = mIdSocio;
    _this['mIdClub'] = mIdClub;
    _this['mClaveVieja'] = mClaveVieja;
    _this['mClaveNueva'] = mClaveNueva;
  };

  /**
   * Constructs a <code>ChangePassword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChangePassword} obj Optional instance to populate.
   * @return {module:model/ChangePassword} The populated <code>ChangePassword</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mIdSocio')) {
        obj['mIdSocio'] = ApiClient.convertToType(data['mIdSocio'], 'String');
      }
      if (data.hasOwnProperty('mIdClub')) {
        obj['mIdClub'] = ApiClient.convertToType(data['mIdClub'], 'String');
      }
      if (data.hasOwnProperty('mClaveVieja')) {
        obj['mClaveVieja'] = ApiClient.convertToType(data['mClaveVieja'], 'String');
      }
      if (data.hasOwnProperty('mClaveNueva')) {
        obj['mClaveNueva'] = ApiClient.convertToType(data['mClaveNueva'], 'String');
      }
    }
    return obj;
  }

  /**
   * User's ID
   * @member {String} mIdSocio
   */
  exports.prototype['mIdSocio'] = undefined;
  /**
   * clubID
   * @member {String} mIdClub
   */
  exports.prototype['mIdClub'] = undefined;
  /**
   * Previous Password
   * @member {String} mClaveVieja
   */
  exports.prototype['mClaveVieja'] = undefined;
  /**
   * New Password
   * @member {String} mClaveNueva
   */
  exports.prototype['mClaveNueva'] = undefined;



  return exports;
}));


