/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Subsidiary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Subsidiary'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.CityLocations = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Subsidiary);
  }
}(this, function(ApiClient, Subsidiary) {
  'use strict';




  /**
   * The CityLocations model module.
   * @module model/CityLocations
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>CityLocations</code>.
   * @alias module:model/CityLocations
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CityLocations</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CityLocations} obj Optional instance to populate.
   * @return {module:model/CityLocations} The populated <code>CityLocations</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('NombreLocalidad')) {
        obj['NombreLocalidad'] = ApiClient.convertToType(data['NombreLocalidad'], 'String');
      }
      if (data.hasOwnProperty('obj_sucursalDetalle')) {
        obj['obj_sucursalDetalle'] = ApiClient.convertToType(data['obj_sucursalDetalle'], [Subsidiary]);
      }
    }
    return obj;
  }

  /**
   * @member {String} NombreLocalidad
   */
  exports.prototype['NombreLocalidad'] = undefined;
  /**
   * @member {Array.<module:model/Subsidiary>} obj_sucursalDetalle
   */
  exports.prototype['obj_sucursalDetalle'] = undefined;



  return exports;
}));


