/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.ClubUserbyIDRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClubUserbyIDRequest model module.
   * @module model/ClubUserbyIDRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>ClubUserbyIDRequest</code>.
   * @alias module:model/ClubUserbyIDRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ClubUserbyIDRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClubUserbyIDRequest} obj Optional instance to populate.
   * @return {module:model/ClubUserbyIDRequest} The populated <code>ClubUserbyIDRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;



  return exports;
}));


