/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Respuesta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Respuesta'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.ContactResponse = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Respuesta);
  }
}(this, function(ApiClient, Respuesta) {
  'use strict';




  /**
   * The ContactResponse model module.
   * @module model/ContactResponse
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>ContactResponse</code>.
   * @alias module:model/ContactResponse
   * @class
   * @param respuesta {module:model/Respuesta} 
   */
  var exports = function(respuesta) {
    var _this = this;

    _this['Respuesta'] = respuesta;
  };

  /**
   * Constructs a <code>ContactResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContactResponse} obj Optional instance to populate.
   * @return {module:model/ContactResponse} The populated <code>ContactResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Respuesta')) {
        obj['Respuesta'] = Respuesta.constructFromObject(data['Respuesta']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Respuesta} Respuesta
   */
  exports.prototype['Respuesta'] = undefined;



  return exports;
}));


