/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.CreditInstance = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreditInstance model module.
   * @module model/CreditInstance
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>CreditInstance</code>.
   * @alias module:model/CreditInstance
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>CreditInstance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreditInstance} obj Optional instance to populate.
   * @return {module:model/CreditInstance} The populated <code>CreditInstance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'String');
      }
      if (data.hasOwnProperty('fk_socio')) {
        obj['fk_socio'] = ApiClient.convertToType(data['fk_socio'], 'String');
      }
      if (data.hasOwnProperty('socio')) {
        obj['socio'] = ApiClient.convertToType(data['socio'], 'String');
      }
      if (data.hasOwnProperty('fecha')) {
        obj['fecha'] = ApiClient.convertToType(data['fecha'], 'String');
      }
      if (data.hasOwnProperty('concepto')) {
        obj['concepto'] = ApiClient.convertToType(data['concepto'], 'String');
      }
      if (data.hasOwnProperty('fk_tipo_instancia')) {
        obj['fk_tipo_instancia'] = ApiClient.convertToType(data['fk_tipo_instancia'], 'String');
      }
      if (data.hasOwnProperty('tipo_instancia')) {
        obj['tipo_instancia'] = ApiClient.convertToType(data['tipo_instancia'], 'String');
      }
      if (data.hasOwnProperty('observaciones')) {
        obj['observaciones'] = ApiClient.convertToType(data['observaciones'], 'String');
      }
      if (data.hasOwnProperty('fechaCarga')) {
        obj['fechaCarga'] = ApiClient.convertToType(data['fechaCarga'], 'String');
      }
      if (data.hasOwnProperty('usuario')) {
        obj['usuario'] = ApiClient.convertToType(data['usuario'], 'String');
      }
      if (data.hasOwnProperty('importe')) {
        obj['importe'] = ApiClient.convertToType(data['importe'], 'String');
      }
      if (data.hasOwnProperty('fk_credito')) {
        obj['fk_credito'] = ApiClient.convertToType(data['fk_credito'], 'String');
      }
      if (data.hasOwnProperty('cuotasRestantes')) {
        obj['cuotasRestantes'] = ApiClient.convertToType(data['cuotasRestantes'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} pk
   */
  exports.prototype['pk'] = undefined;
  /**
   * @member {String} fk_socio
   */
  exports.prototype['fk_socio'] = undefined;
  /**
   * @member {String} socio
   */
  exports.prototype['socio'] = undefined;
  /**
   * @member {String} fecha
   */
  exports.prototype['fecha'] = undefined;
  /**
   * @member {String} concepto
   */
  exports.prototype['concepto'] = undefined;
  /**
   * @member {String} fk_tipo_instancia
   */
  exports.prototype['fk_tipo_instancia'] = undefined;
  /**
   * @member {String} tipo_instancia
   */
  exports.prototype['tipo_instancia'] = undefined;
  /**
   * @member {String} observaciones
   */
  exports.prototype['observaciones'] = undefined;
  /**
   * @member {String} fechaCarga
   */
  exports.prototype['fechaCarga'] = undefined;
  /**
   * @member {String} usuario
   */
  exports.prototype['usuario'] = undefined;
  /**
   * @member {String} importe
   */
  exports.prototype['importe'] = undefined;
  /**
   * @member {String} fk_credito
   */
  exports.prototype['fk_credito'] = undefined;
  /**
   * @member {String} cuotasRestantes
   */
  exports.prototype['cuotasRestantes'] = undefined;



  return exports;
}));


