/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.DeviceInfo = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceInfo model module.
   * @module model/DeviceInfo
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>DeviceInfo</code>.
   * @alias module:model/DeviceInfo
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DeviceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInfo} obj Optional instance to populate.
   * @return {module:model/DeviceInfo} The populated <code>DeviceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('gcm_id')) {
        obj['gcm_id'] = ApiClient.convertToType(data['gcm_id'], 'String');
      }
      if (data.hasOwnProperty('SO')) {
        obj['SO'] = ApiClient.convertToType(data['SO'], 'String');
      }
      if (data.hasOwnProperty('versionApp')) {
        obj['versionApp'] = ApiClient.convertToType(data['versionApp'], 'String');
      }
      if (data.hasOwnProperty('versionSO')) {
        obj['versionSO'] = ApiClient.convertToType(data['versionSO'], 'String');
      }
    }
    return obj;
  }

  /**
   * fcm id
   * @member {String} gcm_id
   */
  exports.prototype['gcm_id'] = undefined;
  /**
   * OS name
   * @member {String} SO
   */
  exports.prototype['SO'] = undefined;
  /**
   * App version
   * @member {String} versionApp
   */
  exports.prototype['versionApp'] = undefined;
  /**
   * OS version
   * @member {String} versionSO
   */
  exports.prototype['versionSO'] = undefined;



  return exports;
}));


