/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.EmailVoucher = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EmailVoucher model module.
   * @module model/EmailVoucher
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>EmailVoucher</code>.
   * @alias module:model/EmailVoucher
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>EmailVoucher</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailVoucher} obj Optional instance to populate.
   * @return {module:model/EmailVoucher} The populated <code>EmailVoucher</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mail1')) {
        obj['mail1'] = ApiClient.convertToType(data['mail1'], 'String');
      }
      if (data.hasOwnProperty('mail2')) {
        obj['mail2'] = ApiClient.convertToType(data['mail2'], 'String');
      }
      if (data.hasOwnProperty('fk_cupon')) {
        obj['fk_cupon'] = ApiClient.convertToType(data['fk_cupon'], 'String');
      }
    }
    return obj;
  }

  /**
   * Email where the voucher should be sent
   * @member {String} mail1
   */
  exports.prototype['mail1'] = undefined;
  /**
   * Alternative email where the voucher should be sent
   * @member {String} mail2
   */
  exports.prototype['mail2'] = undefined;
  /**
   * Voucher ID to be redeemed
   * @member {String} fk_cupon
   */
  exports.prototype['fk_cupon'] = undefined;



  return exports;
}));


