/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Exchange = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Exchange model module.
   * @module model/Exchange
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Exchange</code>.
   * @alias module:model/Exchange
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Exchange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exchange} obj Optional instance to populate.
   * @return {module:model/Exchange} The populated <code>Exchange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdMovimiento')) {
        obj['IdMovimiento'] = ApiClient.convertToType(data['IdMovimiento'], 'String');
      }
      if (data.hasOwnProperty('Fecha de Carga')) {
        obj['Fecha de Carga'] = ApiClient.convertToType(data['Fecha de Carga'], 'String');
      }
      if (data.hasOwnProperty('Carga')) {
        obj['Carga'] = ApiClient.convertToType(data['Carga'], 'String');
      }
      if (data.hasOwnProperty('Saldo')) {
        obj['Saldo'] = ApiClient.convertToType(data['Saldo'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} IdMovimiento
   */
  exports.prototype['IdMovimiento'] = undefined;
  /**
   * @member {String} Fecha de Carga
   */
  exports.prototype['Fecha de Carga'] = undefined;
  /**
   * @member {String} Carga
   */
  exports.prototype['Carga'] = undefined;
  /**
   * @member {String} Saldo
   */
  exports.prototype['Saldo'] = undefined;



  return exports;
}));


