/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Modules = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Modules model module.
   * @module model/Modules
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Modules</code>.
   * @alias module:model/Modules
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>Modules</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Modules} obj Optional instance to populate.
   * @return {module:model/Modules} The populated <code>Modules</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pantallaInicio')) {
        obj['pantallaInicio'] = ApiClient.convertToType(data['pantallaInicio'], 'String');
      }
      if (data.hasOwnProperty('giftCards')) {
        obj['giftCards'] = ApiClient.convertToType(data['giftCards'], 'String');
      }
      if (data.hasOwnProperty('cupones')) {
        obj['cupones'] = ApiClient.convertToType(data['cupones'], 'String');
      }
      if (data.hasOwnProperty('tratamientos')) {
        obj['tratamientos'] = ApiClient.convertToType(data['tratamientos'], 'String');
      }
      if (data.hasOwnProperty('sesiones')) {
        obj['sesiones'] = ApiClient.convertToType(data['sesiones'], 'String');
      }
      if (data.hasOwnProperty('codigoBarra')) {
        obj['codigoBarra'] = ApiClient.convertToType(data['codigoBarra'], 'String');
      }
      if (data.hasOwnProperty('concurso')) {
        obj['concurso'] = ApiClient.convertToType(data['concurso'], 'String');
      }
      if (data.hasOwnProperty('FormularioAltaWeb')) {
        obj['FormularioAltaWeb'] = ApiClient.convertToType(data['FormularioAltaWeb'], 'String');
      }
      if (data.hasOwnProperty('sorteos')) {
        obj['sorteos'] = ApiClient.convertToType(data['sorteos'], 'String');
      }
      if (data.hasOwnProperty('noticias')) {
        obj['noticias'] = ApiClient.convertToType(data['noticias'], 'String');
      }
      if (data.hasOwnProperty('listadoSucursales')) {
        obj['listadoSucursales'] = ApiClient.convertToType(data['listadoSucursales'], 'String');
      }
      if (data.hasOwnProperty('tituloBotonConcurso')) {
        obj['tituloBotonConcurso'] = ApiClient.convertToType(data['tituloBotonConcurso'], 'String');
      }
      if (data.hasOwnProperty('descripcionBotonConcurso')) {
        obj['descripcionBotonConcurso'] = ApiClient.convertToType(data['descripcionBotonConcurso'], 'String');
      }
      if (data.hasOwnProperty('pkConcurso')) {
        obj['pkConcurso'] = ApiClient.convertToType(data['pkConcurso'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} pantallaInicio
   */
  exports.prototype['pantallaInicio'] = undefined;
  /**
   * @member {String} giftCards
   */
  exports.prototype['giftCards'] = undefined;
  /**
   * @member {String} cupones
   */
  exports.prototype['cupones'] = undefined;
  /**
   * @member {String} tratamientos
   */
  exports.prototype['tratamientos'] = undefined;
  /**
   * @member {String} sesiones
   */
  exports.prototype['sesiones'] = undefined;
  /**
   * @member {String} codigoBarra
   */
  exports.prototype['codigoBarra'] = undefined;
  /**
   * @member {String} concurso
   */
  exports.prototype['concurso'] = undefined;
  /**
   * @member {String} FormularioAltaWeb
   */
  exports.prototype['FormularioAltaWeb'] = undefined;
  /**
   * @member {String} sorteos
   */
  exports.prototype['sorteos'] = undefined;
  /**
   * @member {String} noticias
   */
  exports.prototype['noticias'] = undefined;
  /**
   * @member {String} listadoSucursales
   */
  exports.prototype['listadoSucursales'] = undefined;
  /**
   * @member {String} tituloBotonConcurso
   */
  exports.prototype['tituloBotonConcurso'] = undefined;
  /**
   * @member {String} descripcionBotonConcurso
   */
  exports.prototype['descripcionBotonConcurso'] = undefined;
  /**
   * @member {String} pkConcurso
   */
  exports.prototype['pkConcurso'] = undefined;



  return exports;
}));


