/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Prize'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Prize'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Premios = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Prize);
  }
}(this, function(ApiClient, Prize) {
  'use strict';




  /**
   * The Premios model module.
   * @module model/Premios
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Premios</code>.
   * @alias module:model/Premios
   * @class
   * @param premios {Array.<module:model/Prize>} 
   */
  var exports = function(premios) {
    var _this = this;

    _this['Premios'] = premios;
  };

  /**
   * Constructs a <code>Premios</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Premios} obj Optional instance to populate.
   * @return {module:model/Premios} The populated <code>Premios</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Premios')) {
        obj['Premios'] = ApiClient.convertToType(data['Premios'], [Prize]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Prize>} Premios
   */
  exports.prototype['Premios'] = undefined;



  return exports;
}));


