/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.PrizeRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PrizeRequest model module.
   * @module model/PrizeRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>PrizeRequest</code>.
   * @alias module:model/PrizeRequest
   * @class
   * @param idClub {String} clubID
   * @param idSocio {String} userID
   * @param idPremio {String} prizeID
   */
  var exports = function(idClub, idSocio, idPremio) {
    var _this = this;

    _this['IdClub'] = idClub;
    _this['IdSocio'] = idSocio;
    _this['IdPremio'] = idPremio;
  };

  /**
   * Constructs a <code>PrizeRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrizeRequest} obj Optional instance to populate.
   * @return {module:model/PrizeRequest} The populated <code>PrizeRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('IdPremio')) {
        obj['IdPremio'] = ApiClient.convertToType(data['IdPremio'], 'String');
      }
    }
    return obj;
  }

  /**
   * clubID
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;
  /**
   * userID
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * prizeID
   * @member {String} IdPremio
   */
  exports.prototype['IdPremio'] = undefined;



  return exports;
}));


