/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.PrizeRedeemRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PrizeRedeemRequest model module.
   * @module model/PrizeRedeemRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>PrizeRedeemRequest</code>.
   * @alias module:model/PrizeRedeemRequest
   * @class
   * @param movimiento {String} transaction type
   * @param idClub {String} clubID
   * @param idSocio {String} userID
   * @param idPremio {String} prizeID
   * @param retiraEn {String} subsidiary in which to claim prize.
   * @param observaciones {String} Observations
   * @param puntos {String} points earned
   * @param pesos {String} cost in ARS
   */
  var exports = function(movimiento, idClub, idSocio, idPremio, retiraEn, observaciones, puntos, pesos) {
    var _this = this;

    _this['Movimiento'] = movimiento;
    _this['IdClub'] = idClub;
    _this['IdSocio'] = idSocio;
    _this['IdPremio'] = idPremio;
    _this['RetiraEn'] = retiraEn;
    _this['Observaciones'] = observaciones;
    _this['Puntos'] = puntos;
    _this['Pesos'] = pesos;
  };

  /**
   * Constructs a <code>PrizeRedeemRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrizeRedeemRequest} obj Optional instance to populate.
   * @return {module:model/PrizeRedeemRequest} The populated <code>PrizeRedeemRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Movimiento')) {
        obj['Movimiento'] = ApiClient.convertToType(data['Movimiento'], 'String');
      }
      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('IdPremio')) {
        obj['IdPremio'] = ApiClient.convertToType(data['IdPremio'], 'String');
      }
      if (data.hasOwnProperty('RetiraEn')) {
        obj['RetiraEn'] = ApiClient.convertToType(data['RetiraEn'], 'String');
      }
      if (data.hasOwnProperty('Observaciones')) {
        obj['Observaciones'] = ApiClient.convertToType(data['Observaciones'], 'String');
      }
      if (data.hasOwnProperty('Puntos')) {
        obj['Puntos'] = ApiClient.convertToType(data['Puntos'], 'String');
      }
      if (data.hasOwnProperty('Pesos')) {
        obj['Pesos'] = ApiClient.convertToType(data['Pesos'], 'String');
      }
    }
    return obj;
  }

  /**
   * transaction type
   * @member {String} Movimiento
   */
  exports.prototype['Movimiento'] = undefined;
  /**
   * clubID
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;
  /**
   * userID
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * prizeID
   * @member {String} IdPremio
   */
  exports.prototype['IdPremio'] = undefined;
  /**
   * subsidiary in which to claim prize.
   * @member {String} RetiraEn
   */
  exports.prototype['RetiraEn'] = undefined;
  /**
   * Observations
   * @member {String} Observaciones
   */
  exports.prototype['Observaciones'] = undefined;
  /**
   * points earned
   * @member {String} Puntos
   */
  exports.prototype['Puntos'] = undefined;
  /**
   * cost in ARS
   * @member {String} Pesos
   */
  exports.prototype['Pesos'] = undefined;



  return exports;
}));


