/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Card', 'model/Rubro', 'model/Subsidiary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Card'), require('./Rubro'), require('./Subsidiary'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Prize = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Card, root.LoyaltyProgramApi.Rubro, root.LoyaltyProgramApi.Subsidiary);
  }
}(this, function(ApiClient, Card, Rubro, Subsidiary) {
  'use strict';




  /**
   * The Prize model module.
   * @module model/Prize
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Prize</code>.
   * @alias module:model/Prize
   * @class
   */
  var exports = function() {
    var _this = this;




































  };

  /**
   * Constructs a <code>Prize</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Prize} obj Optional instance to populate.
   * @return {module:model/Prize} The populated <code>Prize</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pk_Premio')) {
        obj['pk_Premio'] = ApiClient.convertToType(data['pk_Premio'], 'String');
      }
      if (data.hasOwnProperty('fk_ClubPropietario')) {
        obj['fk_ClubPropietario'] = ApiClient.convertToType(data['fk_ClubPropietario'], 'String');
      }
      if (data.hasOwnProperty('FechaCarga')) {
        obj['FechaCarga'] = ApiClient.convertToType(data['FechaCarga'], 'Date');
      }
      if (data.hasOwnProperty('FechaDesde')) {
        obj['FechaDesde'] = ApiClient.convertToType(data['FechaDesde'], 'Date');
      }
      if (data.hasOwnProperty('FechaHasta')) {
        obj['FechaHasta'] = ApiClient.convertToType(data['FechaHasta'], 'Date');
      }
      if (data.hasOwnProperty('VencimientoCanje')) {
        obj['VencimientoCanje'] = ApiClient.convertToType(data['VencimientoCanje'], 'String');
      }
      if (data.hasOwnProperty('CuentaRegresivaVisible')) {
        obj['CuentaRegresivaVisible'] = ApiClient.convertToType(data['CuentaRegresivaVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('Stock')) {
        obj['Stock'] = ApiClient.convertToType(data['Stock'], 'String');
      }
      if (data.hasOwnProperty('StockVisible')) {
        obj['StockVisible'] = ApiClient.convertToType(data['StockVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('PersonasCanjesVisible')) {
        obj['PersonasCanjesVisible'] = ApiClient.convertToType(data['PersonasCanjesVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('PersonasCanje')) {
        obj['PersonasCanje'] = ApiClient.convertToType(data['PersonasCanje'], 'String');
      }
      if (data.hasOwnProperty('PersonasBaseCanje')) {
        obj['PersonasBaseCanje'] = ApiClient.convertToType(data['PersonasBaseCanje'], 'String');
      }
      if (data.hasOwnProperty('Titulo')) {
        obj['Titulo'] = ApiClient.convertToType(data['Titulo'], 'String');
      }
      if (data.hasOwnProperty('Descripcion')) {
        obj['Descripcion'] = ApiClient.convertToType(data['Descripcion'], 'String');
      }
      if (data.hasOwnProperty('Puntos')) {
        obj['Puntos'] = ApiClient.convertToType(data['Puntos'], 'String');
      }
      if (data.hasOwnProperty('MasPuntos')) {
        obj['MasPuntos'] = ApiClient.convertToType(data['MasPuntos'], 'String');
      }
      if (data.hasOwnProperty('MasPesos')) {
        obj['MasPesos'] = ApiClient.convertToType(data['MasPesos'], 'String');
      }
      if (data.hasOwnProperty('VigenteManual')) {
        obj['VigenteManual'] = ApiClient.convertToType(data['VigenteManual'], 'Boolean');
      }
      if (data.hasOwnProperty('fk_UsuarioCarga')) {
        obj['fk_UsuarioCarga'] = ApiClient.convertToType(data['fk_UsuarioCarga'], 'String');
      }
      if (data.hasOwnProperty('NivelVisible')) {
        obj['NivelVisible'] = ApiClient.convertToType(data['NivelVisible'], 'String');
      }
      if (data.hasOwnProperty('VigenteParaCampaniasInternas')) {
        obj['VigenteParaCampaniasInternas'] = ApiClient.convertToType(data['VigenteParaCampaniasInternas'], 'Boolean');
      }
      if (data.hasOwnProperty('Comportamiento')) {
        obj['Comportamiento'] = ApiClient.convertToType(data['Comportamiento'], 'String');
      }
      if (data.hasOwnProperty('CalificacionVisible')) {
        obj['CalificacionVisible'] = ApiClient.convertToType(data['CalificacionVisible'], 'Boolean');
      }
      if (data.hasOwnProperty('Calificacion')) {
        obj['Calificacion'] = ApiClient.convertToType(data['Calificacion'], 'String');
      }
      if (data.hasOwnProperty('PalabrasClaves')) {
        obj['PalabrasClaves'] = ApiClient.convertToType(data['PalabrasClaves'], 'String');
      }
      if (data.hasOwnProperty('Destacado')) {
        obj['Destacado'] = ApiClient.convertToType(data['Destacado'], 'Boolean');
      }
      if (data.hasOwnProperty('Visitas')) {
        obj['Visitas'] = ApiClient.convertToType(data['Visitas'], 'Number');
      }
      if (data.hasOwnProperty('ArrSucursales')) {
        obj['ArrSucursales'] = ApiClient.convertToType(data['ArrSucursales'], [Subsidiary]);
      }
      if (data.hasOwnProperty('ArrRubros')) {
        obj['ArrRubros'] = ApiClient.convertToType(data['ArrRubros'], [Rubro]);
      }
      if (data.hasOwnProperty('ArrTarjetas')) {
        obj['ArrTarjetas'] = ApiClient.convertToType(data['ArrTarjetas'], [Card]);
      }
      if (data.hasOwnProperty('Distancia')) {
        obj['Distancia'] = ApiClient.convertToType(data['Distancia'], 'String');
      }
      if (data.hasOwnProperty('Descuento')) {
        obj['Descuento'] = ApiClient.convertToType(data['Descuento'], 'String');
      }
      if (data.hasOwnProperty('Frase')) {
        obj['Frase'] = ApiClient.convertToType(data['Frase'], 'String');
      }
      if (data.hasOwnProperty('LinkCorporativo')) {
        obj['LinkCorporativo'] = ApiClient.convertToType(data['LinkCorporativo'], 'String');
      }
      if (data.hasOwnProperty('NombreBoton')) {
        obj['NombreBoton'] = ApiClient.convertToType(data['NombreBoton'], 'String');
      }
    }
    return obj;
  }

  /**
   * Prize ID
   * @member {String} pk_Premio
   */
  exports.prototype['pk_Premio'] = undefined;
  /**
   * clubID to which the prize belongs
   * @member {String} fk_ClubPropietario
   */
  exports.prototype['fk_ClubPropietario'] = undefined;
  /**
   * Date in which the prize was created.
   * @member {Date} FechaCarga
   */
  exports.prototype['FechaCarga'] = undefined;
  /**
   * Date from which the prize will be valid.
   * @member {Date} FechaDesde
   */
  exports.prototype['FechaDesde'] = undefined;
  /**
   * Date until the prize will be available in the catalogue.
   * @member {Date} FechaHasta
   */
  exports.prototype['FechaHasta'] = undefined;
  /**
   * Number of days the user has to access the prize after it has been redeemed.
   * @member {String} VencimientoCanje
   */
  exports.prototype['VencimientoCanje'] = undefined;
  /**
   * If a countdown will be visible for the user. (NOT IMPORTANT)
   * @member {Boolean} CuentaRegresivaVisible
   */
  exports.prototype['CuentaRegresivaVisible'] = undefined;
  /**
   * Ammount of stock of prizes that can be redeemed. (NOT IMPORTANT)
   * @member {String} Stock
   */
  exports.prototype['Stock'] = undefined;
  /**
   * Determins if the ammount of stock will be visible for the user. (NOT IMPORTANT)
   * @member {Boolean} StockVisible
   */
  exports.prototype['StockVisible'] = undefined;
  /**
   * Determins if number of redemptions by other users will be show. (NOT IMPORTANT)
   * @member {Boolean} PersonasCanjesVisible
   */
  exports.prototype['PersonasCanjesVisible'] = undefined;
  /**
   * Number of users that have redeemed this prize. (NOT IMPORTANT)
   * @member {String} PersonasCanje
   */
  exports.prototype['PersonasCanje'] = undefined;
  /**
   * Base number to show of redeemed prizes(NOT IMPORTANT)
   * @member {String} PersonasBaseCanje
   */
  exports.prototype['PersonasBaseCanje'] = undefined;
  /**
   * Prize title.
   * @member {String} Titulo
   */
  exports.prototype['Titulo'] = undefined;
  /**
   * Prize Description.
   * @member {String} Descripcion
   */
  exports.prototype['Descripcion'] = undefined;
  /**
   * Points needed to redeem the prize. (NOT IMPORTANT)
   * @member {String} Puntos
   */
  exports.prototype['Puntos'] = undefined;
  /**
   * Points needed to redeem the prize if paying part in cash. (NOT IMPORTANT)
   * @member {String} MasPuntos
   */
  exports.prototype['MasPuntos'] = undefined;
  /**
   * Cash needed to redeem the prize if paying part in points. (NOT IMPORTANT)
   * @member {String} MasPesos
   */
  exports.prototype['MasPesos'] = undefined;
  /**
   * If the prize is available by manual selection.
   * @member {Boolean} VigenteManual
   */
  exports.prototype['VigenteManual'] = undefined;
  /**
   * (NOT IMPORTANT)
   * @member {String} fk_UsuarioCarga
   */
  exports.prototype['fk_UsuarioCarga'] = undefined;
  /**
   * (NOT IMPORTANT)
   * @member {String} NivelVisible
   */
  exports.prototype['NivelVisible'] = undefined;
  /**
   * Available for internal Campaigns.
   * @member {Boolean} VigenteParaCampaniasInternas
   */
  exports.prototype['VigenteParaCampaniasInternas'] = undefined;
  /**
   * How does the prize work. This value sets if the prize will be redeemed or if it will respond with a different beahviour. 2 generates a code. 1 prize redeemed with points. 3 other kind of behaviour (pk_Premio of 9889, 9954).
   * @member {String} Comportamiento
   */
  exports.prototype['Comportamiento'] = undefined;
  /**
   * Prize rating available.
   * @member {Boolean} CalificacionVisible
   */
  exports.prototype['CalificacionVisible'] = undefined;
  /**
   * Prize rating.
   * @member {String} Calificacion
   */
  exports.prototype['Calificacion'] = undefined;
  /**
   * keywords.
   * @member {String} PalabrasClaves
   */
  exports.prototype['PalabrasClaves'] = undefined;
  /**
   * Is featured
   * @member {Boolean} Destacado
   */
  exports.prototype['Destacado'] = undefined;
  /**
   * Ammount of visits.
   * @member {Number} Visitas
   */
  exports.prototype['Visitas'] = undefined;
  /**
   * @member {Array.<module:model/Subsidiary>} ArrSucursales
   */
  exports.prototype['ArrSucursales'] = undefined;
  /**
   * @member {Array.<module:model/Rubro>} ArrRubros
   */
  exports.prototype['ArrRubros'] = undefined;
  /**
   * @member {Array.<module:model/Card>} ArrTarjetas
   */
  exports.prototype['ArrTarjetas'] = undefined;
  /**
   * distance to subsidiary.
   * @member {String} Distancia
   */
  exports.prototype['Distancia'] = undefined;
  /**
   * Discount.
   * @member {String} Descuento
   */
  exports.prototype['Descuento'] = undefined;
  /**
   * Discount text.
   * @member {String} Frase
   */
  exports.prototype['Frase'] = undefined;
  /**
   * Link to external URL
   * @member {String} LinkCorporativo
   */
  exports.prototype['LinkCorporativo'] = undefined;
  /**
   * Button Label
   * @member {String} NombreBoton
   */
  exports.prototype['NombreBoton'] = undefined;



  return exports;
}));


