/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Redemption = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Redemption model module.
   * @module model/Redemption
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Redemption</code>.
   * @alias module:model/Redemption
   * @class
   */
  var exports = function() {
    var _this = this;





























  };

  /**
   * Constructs a <code>Redemption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Redemption} obj Optional instance to populate.
   * @return {module:model/Redemption} The populated <code>Redemption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdCanje')) {
        obj['IdCanje'] = ApiClient.convertToType(data['IdCanje'], 'String');
      }
      if (data.hasOwnProperty('IdClubPremio')) {
        obj['IdClubPremio'] = ApiClient.convertToType(data['IdClubPremio'], 'String');
      }
      if (data.hasOwnProperty('IdClubSocio')) {
        obj['IdClubSocio'] = ApiClient.convertToType(data['IdClubSocio'], 'String');
      }
      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('IdPremio')) {
        obj['IdPremio'] = ApiClient.convertToType(data['IdPremio'], 'String');
      }
      if (data.hasOwnProperty('FechaReserva')) {
        obj['FechaReserva'] = ApiClient.convertToType(data['FechaReserva'], 'String');
      }
      if (data.hasOwnProperty('FechaCanjeado')) {
        obj['FechaCanjeado'] = ApiClient.convertToType(data['FechaCanjeado'], 'String');
      }
      if (data.hasOwnProperty('FechaDevolucion')) {
        obj['FechaDevolucion'] = ApiClient.convertToType(data['FechaDevolucion'], 'String');
      }
      if (data.hasOwnProperty('FechaVencimiento')) {
        obj['FechaVencimiento'] = ApiClient.convertToType(data['FechaVencimiento'], 'String');
      }
      if (data.hasOwnProperty('UsuarioReserva')) {
        obj['UsuarioReserva'] = ApiClient.convertToType(data['UsuarioReserva'], 'String');
      }
      if (data.hasOwnProperty('UsuarioCanje')) {
        obj['UsuarioCanje'] = ApiClient.convertToType(data['UsuarioCanje'], 'String');
      }
      if (data.hasOwnProperty('UsuarioDevolucion')) {
        obj['UsuarioDevolucion'] = ApiClient.convertToType(data['UsuarioDevolucion'], 'String');
      }
      if (data.hasOwnProperty('SucursalReserva')) {
        obj['SucursalReserva'] = ApiClient.convertToType(data['SucursalReserva'], 'String');
      }
      if (data.hasOwnProperty('SucursalCanje')) {
        obj['SucursalCanje'] = ApiClient.convertToType(data['SucursalCanje'], 'String');
      }
      if (data.hasOwnProperty('SucursalDevolucion')) {
        obj['SucursalDevolucion'] = ApiClient.convertToType(data['SucursalDevolucion'], 'String');
      }
      if (data.hasOwnProperty('Observaciones')) {
        obj['Observaciones'] = ApiClient.convertToType(data['Observaciones'], 'String');
      }
      if (data.hasOwnProperty('Puntos')) {
        obj['Puntos'] = ApiClient.convertToType(data['Puntos'], 'String');
      }
      if (data.hasOwnProperty('Pesos')) {
        obj['Pesos'] = ApiClient.convertToType(data['Pesos'], 'String');
      }
      if (data.hasOwnProperty('RetiraEn')) {
        obj['RetiraEn'] = ApiClient.convertToType(data['RetiraEn'], 'String');
      }
      if (data.hasOwnProperty('CodigoCanje')) {
        obj['CodigoCanje'] = ApiClient.convertToType(data['CodigoCanje'], 'String');
      }
      if (data.hasOwnProperty('Titulo')) {
        obj['Titulo'] = ApiClient.convertToType(data['Titulo'], 'String');
      }
      if (data.hasOwnProperty('NombreUsuarioReserva')) {
        obj['NombreUsuarioReserva'] = ApiClient.convertToType(data['NombreUsuarioReserva'], 'String');
      }
      if (data.hasOwnProperty('NombreUsuarioCanje')) {
        obj['NombreUsuarioCanje'] = ApiClient.convertToType(data['NombreUsuarioCanje'], 'String');
      }
      if (data.hasOwnProperty('NombreUsuarioDevolucion')) {
        obj['NombreUsuarioDevolucion'] = ApiClient.convertToType(data['NombreUsuarioDevolucion'], 'String');
      }
      if (data.hasOwnProperty('DomicilioSucursalReserva')) {
        obj['DomicilioSucursalReserva'] = ApiClient.convertToType(data['DomicilioSucursalReserva'], 'String');
      }
      if (data.hasOwnProperty('DomicilioSucursalCanje')) {
        obj['DomicilioSucursalCanje'] = ApiClient.convertToType(data['DomicilioSucursalCanje'], 'String');
      }
      if (data.hasOwnProperty('DomicilioSucursalDevolucion')) {
        obj['DomicilioSucursalDevolucion'] = ApiClient.convertToType(data['DomicilioSucursalDevolucion'], 'String');
      }
      if (data.hasOwnProperty('DomicilioSucursalRetiraEn')) {
        obj['DomicilioSucursalRetiraEn'] = ApiClient.convertToType(data['DomicilioSucursalRetiraEn'], 'String');
      }
    }
    return obj;
  }

  /**
   * redemption id
   * @member {String} IdCanje
   */
  exports.prototype['IdCanje'] = undefined;
  /**
   * Prize's clubID
   * @member {String} IdClubPremio
   */
  exports.prototype['IdClubPremio'] = undefined;
  /**
   * User's clubID
   * @member {String} IdClubSocio
   */
  exports.prototype['IdClubSocio'] = undefined;
  /**
   * User's DB ID
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * Prize ID
   * @member {String} IdPremio
   */
  exports.prototype['IdPremio'] = undefined;
  /**
   * date redeemed
   * @member {String} FechaReserva
   */
  exports.prototype['FechaReserva'] = undefined;
  /**
   * Date Used
   * @member {String} FechaCanjeado
   */
  exports.prototype['FechaCanjeado'] = undefined;
  /**
   * Date Returned
   * @member {String} FechaDevolucion
   */
  exports.prototype['FechaDevolucion'] = undefined;
  /**
   * Valid Thru
   * @member {String} FechaVencimiento
   */
  exports.prototype['FechaVencimiento'] = undefined;
  /**
   * User ID which redeemed the prize
   * @member {String} UsuarioReserva
   */
  exports.prototype['UsuarioReserva'] = undefined;
  /**
   * User Id which used the prize
   * @member {String} UsuarioCanje
   */
  exports.prototype['UsuarioCanje'] = undefined;
  /**
   * User ID which returned the prize
   * @member {String} UsuarioDevolucion
   */
  exports.prototype['UsuarioDevolucion'] = undefined;
  /**
   * Subsidiary of redemption
   * @member {String} SucursalReserva
   */
  exports.prototype['SucursalReserva'] = undefined;
  /**
   * Subsidiary for usage
   * @member {String} SucursalCanje
   */
  exports.prototype['SucursalCanje'] = undefined;
  /**
   * Subsidiary for return
   * @member {String} SucursalDevolucion
   */
  exports.prototype['SucursalDevolucion'] = undefined;
  /**
   * @member {String} Observaciones
   */
  exports.prototype['Observaciones'] = undefined;
  /**
   * Points earned
   * @member {String} Puntos
   */
  exports.prototype['Puntos'] = undefined;
  /**
   * Money earned
   * @member {String} Pesos
   */
  exports.prototype['Pesos'] = undefined;
  /**
   * Subsidiary in which the prize will be used
   * @member {String} RetiraEn
   */
  exports.prototype['RetiraEn'] = undefined;
  /**
   * Redemption Code
   * @member {String} CodigoCanje
   */
  exports.prototype['CodigoCanje'] = undefined;
  /**
   * Prize name
   * @member {String} Titulo
   */
  exports.prototype['Titulo'] = undefined;
  /**
   * User Name for redemption
   * @member {String} NombreUsuarioReserva
   */
  exports.prototype['NombreUsuarioReserva'] = undefined;
  /**
   * User name for usage
   * @member {String} NombreUsuarioCanje
   */
  exports.prototype['NombreUsuarioCanje'] = undefined;
  /**
   * User name for return
   * @member {String} NombreUsuarioDevolucion
   */
  exports.prototype['NombreUsuarioDevolucion'] = undefined;
  /**
   * Redemption Subsidiary address
   * @member {String} DomicilioSucursalReserva
   */
  exports.prototype['DomicilioSucursalReserva'] = undefined;
  /**
   * Usage Subsidairy address
   * @member {String} DomicilioSucursalCanje
   */
  exports.prototype['DomicilioSucursalCanje'] = undefined;
  /**
   * Return subsidiary address
   * @member {String} DomicilioSucursalDevolucion
   */
  exports.prototype['DomicilioSucursalDevolucion'] = undefined;
  /**
   * Address in which the prize will be used.
   * @member {String} DomicilioSucursalRetiraEn
   */
  exports.prototype['DomicilioSucursalRetiraEn'] = undefined;



  return exports;
}));


