/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.RedemptionsRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RedemptionsRequest model module.
   * @module model/RedemptionsRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>RedemptionsRequest</code>.
   * @alias module:model/RedemptionsRequest
   * @class
   * @param idSocio {String} User's DB ID
   * @param vigente {Boolean} is the User Active
   */
  var exports = function(idSocio, vigente) {
    var _this = this;

    _this['IdSocio'] = idSocio;
    _this['Vigente'] = vigente;
  };

  /**
   * Constructs a <code>RedemptionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RedemptionsRequest} obj Optional instance to populate.
   * @return {module:model/RedemptionsRequest} The populated <code>RedemptionsRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('Vigente')) {
        obj['Vigente'] = ApiClient.convertToType(data['Vigente'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * User's DB ID
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * is the User Active
   * @member {Boolean} Vigente
   */
  exports.prototype['Vigente'] = undefined;



  return exports;
}));


