/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Rubro = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Rubro model module.
   * @module model/Rubro
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Rubro</code>.
   * @alias module:model/Rubro
   * @class
   * @param fkRubro {String} ID of the category
   * @param descripcion {String} Description of the category
   * @param urlImagen {String} URL for the background image of the category
   * @param prioridadVisualizacion {String} display priority (order) of the category
   */
  var exports = function(fkRubro, descripcion, urlImagen, prioridadVisualizacion) {
    var _this = this;

    _this['fk_Rubro'] = fkRubro;
    _this['Descripcion'] = descripcion;
    _this['UrlImagen'] = urlImagen;
    _this['PrioridadVisualizacion'] = prioridadVisualizacion;
  };

  /**
   * Constructs a <code>Rubro</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rubro} obj Optional instance to populate.
   * @return {module:model/Rubro} The populated <code>Rubro</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fk_Rubro')) {
        obj['fk_Rubro'] = ApiClient.convertToType(data['fk_Rubro'], 'String');
      }
      if (data.hasOwnProperty('Descripcion')) {
        obj['Descripcion'] = ApiClient.convertToType(data['Descripcion'], 'String');
      }
      if (data.hasOwnProperty('UrlImagen')) {
        obj['UrlImagen'] = ApiClient.convertToType(data['UrlImagen'], 'String');
      }
      if (data.hasOwnProperty('PrioridadVisualizacion')) {
        obj['PrioridadVisualizacion'] = ApiClient.convertToType(data['PrioridadVisualizacion'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of the category
   * @member {String} fk_Rubro
   */
  exports.prototype['fk_Rubro'] = undefined;
  /**
   * Description of the category
   * @member {String} Descripcion
   */
  exports.prototype['Descripcion'] = undefined;
  /**
   * URL for the background image of the category
   * @member {String} UrlImagen
   */
  exports.prototype['UrlImagen'] = undefined;
  /**
   * display priority (order) of the category
   * @member {String} PrioridadVisualizacion
   */
  exports.prototype['PrioridadVisualizacion'] = undefined;



  return exports;
}));


