/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Rubro'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Rubro'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Rubros = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Rubro);
  }
}(this, function(ApiClient, Rubro) {
  'use strict';




  /**
   * The Rubros model module.
   * @module model/Rubros
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Rubros</code>.
   * @alias module:model/Rubros
   * @class
   * @param rubros {Array.<module:model/Rubro>} 
   */
  var exports = function(rubros) {
    var _this = this;

    _this['Rubros'] = rubros;
  };

  /**
   * Constructs a <code>Rubros</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rubros} obj Optional instance to populate.
   * @return {module:model/Rubros} The populated <code>Rubros</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Rubros')) {
        obj['Rubros'] = ApiClient.convertToType(data['Rubros'], [Rubro]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Rubro>} Rubros
   */
  exports.prototype['Rubros'] = undefined;



  return exports;
}));


