/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SubsidiaryPremio'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SubsidiaryPremio'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Subsidiary = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.SubsidiaryPremio);
  }
}(this, function(ApiClient, SubsidiaryPremio) {
  'use strict';




  /**
   * The Subsidiary model module.
   * @module model/Subsidiary
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Subsidiary</code>.
   * @alias module:model/Subsidiary
   * @class
   */
  var exports = function() {
    var _this = this;



























  };

  /**
   * Constructs a <code>Subsidiary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subsidiary} obj Optional instance to populate.
   * @return {module:model/Subsidiary} The populated <code>Subsidiary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdSucursal')) {
        obj['IdSucursal'] = ApiClient.convertToType(data['IdSucursal'], 'String');
      }
      if (data.hasOwnProperty('pk_Sucursal')) {
        obj['pk_Sucursal'] = ApiClient.convertToType(data['pk_Sucursal'], 'String');
      }
      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
      if (data.hasOwnProperty('fk_Club')) {
        obj['fk_Club'] = ApiClient.convertToType(data['fk_Club'], 'String');
      }
      if (data.hasOwnProperty('DescripcionSucursal')) {
        obj['DescripcionSucursal'] = ApiClient.convertToType(data['DescripcionSucursal'], 'String');
      }
      if (data.hasOwnProperty('DomicilioSucursal')) {
        obj['DomicilioSucursal'] = ApiClient.convertToType(data['DomicilioSucursal'], 'String');
      }
      if (data.hasOwnProperty('Visible')) {
        obj['Visible'] = ApiClient.convertToType(data['Visible'], 'String');
      }
      if (data.hasOwnProperty('Latitud')) {
        obj['Latitud'] = ApiClient.convertToType(data['Latitud'], 'String');
      }
      if (data.hasOwnProperty('Longitud')) {
        obj['Longitud'] = ApiClient.convertToType(data['Longitud'], 'String');
      }
      if (data.hasOwnProperty('NombreParaMapa')) {
        obj['NombreParaMapa'] = ApiClient.convertToType(data['NombreParaMapa'], 'String');
      }
      if (data.hasOwnProperty('DireccionParaMapa')) {
        obj['DireccionParaMapa'] = ApiClient.convertToType(data['DireccionParaMapa'], 'String');
      }
      if (data.hasOwnProperty('IframeMapa')) {
        obj['IframeMapa'] = ApiClient.convertToType(data['IframeMapa'], 'String');
      }
      if (data.hasOwnProperty('DatosAdicionales')) {
        obj['DatosAdicionales'] = ApiClient.convertToType(data['DatosAdicionales'], 'String');
      }
      if (data.hasOwnProperty('multiSucursal')) {
        obj['multiSucursal'] = ApiClient.convertToType(data['multiSucursal'], 'String');
      }
      if (data.hasOwnProperty('imagenMulti')) {
        obj['imagenMulti'] = ApiClient.convertToType(data['imagenMulti'], 'String');
      }
      if (data.hasOwnProperty('premio')) {
        obj['premio'] = SubsidiaryPremio.constructFromObject(data['premio']);
      }
      if (data.hasOwnProperty('AppHorario')) {
        obj['AppHorario'] = ApiClient.convertToType(data['AppHorario'], 'String');
      }
      if (data.hasOwnProperty('AppDireccion')) {
        obj['AppDireccion'] = ApiClient.convertToType(data['AppDireccion'], 'String');
      }
      if (data.hasOwnProperty('AppTelefono1')) {
        obj['AppTelefono1'] = ApiClient.convertToType(data['AppTelefono1'], 'String');
      }
      if (data.hasOwnProperty('AppTelefono2')) {
        obj['AppTelefono2'] = ApiClient.convertToType(data['AppTelefono2'], 'String');
      }
      if (data.hasOwnProperty('AppFacebook')) {
        obj['AppFacebook'] = ApiClient.convertToType(data['AppFacebook'], 'String');
      }
      if (data.hasOwnProperty('AppTwitter')) {
        obj['AppTwitter'] = ApiClient.convertToType(data['AppTwitter'], 'String');
      }
      if (data.hasOwnProperty('AppInstagram')) {
        obj['AppInstagram'] = ApiClient.convertToType(data['AppInstagram'], 'String');
      }
      if (data.hasOwnProperty('AppYoutube')) {
        obj['AppYoutube'] = ApiClient.convertToType(data['AppYoutube'], 'String');
      }
      if (data.hasOwnProperty('AppGooglePlus')) {
        obj['AppGooglePlus'] = ApiClient.convertToType(data['AppGooglePlus'], 'String');
      }
      if (data.hasOwnProperty('AppWeb')) {
        obj['AppWeb'] = ApiClient.convertToType(data['AppWeb'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} IdSucursal
   */
  exports.prototype['IdSucursal'] = undefined;
  /**
   * @member {String} pk_Sucursal
   */
  exports.prototype['pk_Sucursal'] = undefined;
  /**
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;
  /**
   * @member {String} fk_Club
   */
  exports.prototype['fk_Club'] = undefined;
  /**
   * @member {String} DescripcionSucursal
   */
  exports.prototype['DescripcionSucursal'] = undefined;
  /**
   * @member {String} DomicilioSucursal
   */
  exports.prototype['DomicilioSucursal'] = undefined;
  /**
   * @member {String} Visible
   */
  exports.prototype['Visible'] = undefined;
  /**
   * @member {String} Latitud
   */
  exports.prototype['Latitud'] = undefined;
  /**
   * @member {String} Longitud
   */
  exports.prototype['Longitud'] = undefined;
  /**
   * @member {String} NombreParaMapa
   */
  exports.prototype['NombreParaMapa'] = undefined;
  /**
   * @member {String} DireccionParaMapa
   */
  exports.prototype['DireccionParaMapa'] = undefined;
  /**
   * @member {String} IframeMapa
   */
  exports.prototype['IframeMapa'] = undefined;
  /**
   * @member {String} DatosAdicionales
   */
  exports.prototype['DatosAdicionales'] = undefined;
  /**
   * @member {String} multiSucursal
   */
  exports.prototype['multiSucursal'] = undefined;
  /**
   * @member {String} imagenMulti
   */
  exports.prototype['imagenMulti'] = undefined;
  /**
   * @member {module:model/SubsidiaryPremio} premio
   */
  exports.prototype['premio'] = undefined;
  /**
   * @member {String} AppHorario
   */
  exports.prototype['AppHorario'] = undefined;
  /**
   * @member {String} AppDireccion
   */
  exports.prototype['AppDireccion'] = undefined;
  /**
   * @member {String} AppTelefono1
   */
  exports.prototype['AppTelefono1'] = undefined;
  /**
   * @member {String} AppTelefono2
   */
  exports.prototype['AppTelefono2'] = undefined;
  /**
   * @member {String} AppFacebook
   */
  exports.prototype['AppFacebook'] = undefined;
  /**
   * @member {String} AppTwitter
   */
  exports.prototype['AppTwitter'] = undefined;
  /**
   * @member {String} AppInstagram
   */
  exports.prototype['AppInstagram'] = undefined;
  /**
   * @member {String} AppYoutube
   */
  exports.prototype['AppYoutube'] = undefined;
  /**
   * @member {String} AppGooglePlus
   */
  exports.prototype['AppGooglePlus'] = undefined;
  /**
   * @member {String} AppWeb
   */
  exports.prototype['AppWeb'] = undefined;



  return exports;
}));


