/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.SweepstakeUser = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SweepstakeUser model module.
   * @module model/SweepstakeUser
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>SweepstakeUser</code>.
   * @alias module:model/SweepstakeUser
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SweepstakeUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SweepstakeUser} obj Optional instance to populate.
   * @return {module:model/SweepstakeUser} The populated <code>SweepstakeUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fk_concurso')) {
        obj['fk_concurso'] = ApiClient.convertToType(data['fk_concurso'], 'String');
      }
      if (data.hasOwnProperty('fk_socio')) {
        obj['fk_socio'] = ApiClient.convertToType(data['fk_socio'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} fk_concurso
   */
  exports.prototype['fk_concurso'] = undefined;
  /**
   * @member {String} fk_socio
   */
  exports.prototype['fk_socio'] = undefined;



  return exports;
}));


