/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Ticket = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Ticket model module.
   * @module model/Ticket
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Ticket</code>.
   * @alias module:model/Ticket
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>Ticket</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ticket} obj Optional instance to populate.
   * @return {module:model/Ticket} The populated <code>Ticket</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdMovimiento')) {
        obj['IdMovimiento'] = ApiClient.convertToType(data['IdMovimiento'], 'String');
      }
      if (data.hasOwnProperty('DescripcionSucursal')) {
        obj['DescripcionSucursal'] = ApiClient.convertToType(data['DescripcionSucursal'], 'String');
      }
      if (data.hasOwnProperty('Usuario')) {
        obj['Usuario'] = ApiClient.convertToType(data['Usuario'], 'String');
      }
      if (data.hasOwnProperty('Fecha')) {
        obj['Fecha'] = ApiClient.convertToType(data['Fecha'], 'String');
      }
      if (data.hasOwnProperty('Hora')) {
        obj['Hora'] = ApiClient.convertToType(data['Hora'], 'String');
      }
      if (data.hasOwnProperty('Movimiento')) {
        obj['Movimiento'] = ApiClient.convertToType(data['Movimiento'], 'String');
      }
      if (data.hasOwnProperty('Ticket')) {
        obj['Ticket'] = ApiClient.convertToType(data['Ticket'], 'String');
      }
      if (data.hasOwnProperty('ImporteCompra')) {
        obj['ImporteCompra'] = ApiClient.convertToType(data['ImporteCompra'], 'String');
      }
      if (data.hasOwnProperty('PuntosCarga')) {
        obj['PuntosCarga'] = ApiClient.convertToType(data['PuntosCarga'], 'String');
      }
      if (data.hasOwnProperty('PuntosAntesCarga')) {
        obj['PuntosAntesCarga'] = ApiClient.convertToType(data['PuntosAntesCarga'], 'String');
      }
      if (data.hasOwnProperty('PuntosDespuesCarga')) {
        obj['PuntosDespuesCarga'] = ApiClient.convertToType(data['PuntosDespuesCarga'], 'String');
      }
      if (data.hasOwnProperty('Detalle')) {
        obj['Detalle'] = ApiClient.convertToType(data['Detalle'], 'String');
      }
      if (data.hasOwnProperty('Anulado')) {
        obj['Anulado'] = ApiClient.convertToType(data['Anulado'], 'String');
      }
      if (data.hasOwnProperty('UsuarioAnula')) {
        obj['UsuarioAnula'] = ApiClient.convertToType(data['UsuarioAnula'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} IdMovimiento
   */
  exports.prototype['IdMovimiento'] = undefined;
  /**
   * @member {String} DescripcionSucursal
   */
  exports.prototype['DescripcionSucursal'] = undefined;
  /**
   * @member {String} Usuario
   */
  exports.prototype['Usuario'] = undefined;
  /**
   * @member {String} Fecha
   */
  exports.prototype['Fecha'] = undefined;
  /**
   * @member {String} Hora
   */
  exports.prototype['Hora'] = undefined;
  /**
   * @member {String} Movimiento
   */
  exports.prototype['Movimiento'] = undefined;
  /**
   * @member {String} Ticket
   */
  exports.prototype['Ticket'] = undefined;
  /**
   * @member {String} ImporteCompra
   */
  exports.prototype['ImporteCompra'] = undefined;
  /**
   * @member {String} PuntosCarga
   */
  exports.prototype['PuntosCarga'] = undefined;
  /**
   * @member {String} PuntosAntesCarga
   */
  exports.prototype['PuntosAntesCarga'] = undefined;
  /**
   * @member {String} PuntosDespuesCarga
   */
  exports.prototype['PuntosDespuesCarga'] = undefined;
  /**
   * @member {String} Detalle
   */
  exports.prototype['Detalle'] = undefined;
  /**
   * @member {String} Anulado
   */
  exports.prototype['Anulado'] = undefined;
  /**
   * @member {String} UsuarioAnula
   */
  exports.prototype['UsuarioAnula'] = undefined;



  return exports;
}));


