/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.User = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  var exports = function() {
    var _this = this;























  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
      if (data.hasOwnProperty('IdSocio')) {
        obj['IdSocio'] = ApiClient.convertToType(data['IdSocio'], 'String');
      }
      if (data.hasOwnProperty('ApellidoSocio')) {
        obj['ApellidoSocio'] = ApiClient.convertToType(data['ApellidoSocio'], 'String');
      }
      if (data.hasOwnProperty('NombreSocio')) {
        obj['NombreSocio'] = ApiClient.convertToType(data['NombreSocio'], 'String');
      }
      if (data.hasOwnProperty('Sexo')) {
        obj['Sexo'] = ApiClient.convertToType(data['Sexo'], 'String');
      }
      if (data.hasOwnProperty('IdTipoDoc')) {
        obj['IdTipoDoc'] = ApiClient.convertToType(data['IdTipoDoc'], 'String');
      }
      if (data.hasOwnProperty('TipoDocumento')) {
        obj['TipoDocumento'] = ApiClient.convertToType(data['TipoDocumento'], 'String');
      }
      if (data.hasOwnProperty('NumeroDoc')) {
        obj['NumeroDoc'] = ApiClient.convertToType(data['NumeroDoc'], 'String');
      }
      if (data.hasOwnProperty('MailSocio')) {
        obj['MailSocio'] = ApiClient.convertToType(data['MailSocio'], 'String');
      }
      if (data.hasOwnProperty('FechaAlta')) {
        obj['FechaAlta'] = ApiClient.convertToType(data['FechaAlta'], 'Date');
      }
      if (data.hasOwnProperty('FechaNacimiento')) {
        obj['FechaNacimiento'] = ApiClient.convertToType(data['FechaNacimiento'], 'Date');
      }
      if (data.hasOwnProperty('TelefonoSocio')) {
        obj['TelefonoSocio'] = ApiClient.convertToType(data['TelefonoSocio'], 'String');
      }
      if (data.hasOwnProperty('CelularSocio')) {
        obj['CelularSocio'] = ApiClient.convertToType(data['CelularSocio'], 'String');
      }
      if (data.hasOwnProperty('Direccion')) {
        obj['Direccion'] = ApiClient.convertToType(data['Direccion'], 'String');
      }
      if (data.hasOwnProperty('fk_Ciudad')) {
        obj['fk_Ciudad'] = ApiClient.convertToType(data['fk_Ciudad'], 'String');
      }
      if (data.hasOwnProperty('Localidad')) {
        obj['Localidad'] = ApiClient.convertToType(data['Localidad'], 'String');
      }
      if (data.hasOwnProperty('NumeroTarjeta')) {
        obj['NumeroTarjeta'] = ApiClient.convertToType(data['NumeroTarjeta'], 'String');
      }
      if (data.hasOwnProperty('IdTipoTarjeta')) {
        obj['IdTipoTarjeta'] = ApiClient.convertToType(data['IdTipoTarjeta'], 'String');
      }
      if (data.hasOwnProperty('TipoDeTarjeta')) {
        obj['TipoDeTarjeta'] = ApiClient.convertToType(data['TipoDeTarjeta'], 'String');
      }
      if (data.hasOwnProperty('PuntosAcumuladosClub')) {
        obj['PuntosAcumuladosClub'] = ApiClient.convertToType(data['PuntosAcumuladosClub'], 'String');
      }
      if (data.hasOwnProperty('ImagenPerfil')) {
        obj['ImagenPerfil'] = ApiClient.convertToType(data['ImagenPerfil'], 'String');
      }
      if (data.hasOwnProperty('Ocupacion')) {
        obj['Ocupacion'] = ApiClient.convertToType(data['Ocupacion'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;
  /**
   * @member {String} IdSocio
   */
  exports.prototype['IdSocio'] = undefined;
  /**
   * User's surname
   * @member {String} ApellidoSocio
   */
  exports.prototype['ApellidoSocio'] = undefined;
  /**
   * User's name
   * @member {String} NombreSocio
   */
  exports.prototype['NombreSocio'] = undefined;
  /**
   * User's gender
   * @member {String} Sexo
   */
  exports.prototype['Sexo'] = undefined;
  /**
   * User's identification card type ID
   * @member {String} IdTipoDoc
   */
  exports.prototype['IdTipoDoc'] = undefined;
  /**
   * User's identification card type (name)
   * @member {String} TipoDocumento
   */
  exports.prototype['TipoDocumento'] = undefined;
  /**
   * User's identification card number
   * @member {String} NumeroDoc
   */
  exports.prototype['NumeroDoc'] = undefined;
  /**
   * User's email address
   * @member {String} MailSocio
   */
  exports.prototype['MailSocio'] = undefined;
  /**
   * User creation datetime
   * @member {Date} FechaAlta
   */
  exports.prototype['FechaAlta'] = undefined;
  /**
   * User's birth date
   * @member {Date} FechaNacimiento
   */
  exports.prototype['FechaNacimiento'] = undefined;
  /**
   * User's phone number
   * @member {String} TelefonoSocio
   */
  exports.prototype['TelefonoSocio'] = undefined;
  /**
   * User's cellphone number
   * @member {String} CelularSocio
   */
  exports.prototype['CelularSocio'] = undefined;
  /**
   * User's address
   * @member {String} Direccion
   */
  exports.prototype['Direccion'] = undefined;
  /**
   * User's city ID
   * @member {String} fk_Ciudad
   */
  exports.prototype['fk_Ciudad'] = undefined;
  /**
   * User's city name.
   * @member {String} Localidad
   */
  exports.prototype['Localidad'] = undefined;
  /**
   * User's loyalty card number.
   * @member {String} NumeroTarjeta
   */
  exports.prototype['NumeroTarjeta'] = undefined;
  /**
   * Loyalty card type ID
   * @member {String} IdTipoTarjeta
   */
  exports.prototype['IdTipoTarjeta'] = undefined;
  /**
   * Loyalty card type name
   * @member {String} TipoDeTarjeta
   */
  exports.prototype['TipoDeTarjeta'] = undefined;
  /**
   * User's earned points
   * @member {String} PuntosAcumuladosClub
   */
  exports.prototype['PuntosAcumuladosClub'] = undefined;
  /**
   * User's profile picture
   * @member {String} ImagenPerfil
   */
  exports.prototype['ImagenPerfil'] = undefined;
  /**
   * @member {String} Ocupacion
   */
  exports.prototype['Ocupacion'] = undefined;



  return exports;
}));


