/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.UserLoginRequest = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserLoginRequest model module.
   * @module model/UserLoginRequest
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>UserLoginRequest</code>.
   * @alias module:model/UserLoginRequest
   * @class
   * @param claveSocio {String} User password
   * @param idClub {String} 
   */
  var exports = function(claveSocio, idClub) {
    var _this = this;



    _this['ClaveSocio'] = claveSocio;

    _this['IdClub'] = idClub;
  };

  /**
   * Constructs a <code>UserLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserLoginRequest} obj Optional instance to populate.
   * @return {module:model/UserLoginRequest} The populated <code>UserLoginRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TipoDato')) {
        obj['TipoDato'] = ApiClient.convertToType(data['TipoDato'], 'String');
      }
      if (data.hasOwnProperty('NumeroDato')) {
        obj['NumeroDato'] = ApiClient.convertToType(data['NumeroDato'], 'String');
      }
      if (data.hasOwnProperty('ClaveSocio')) {
        obj['ClaveSocio'] = ApiClient.convertToType(data['ClaveSocio'], 'String');
      }
      if (data.hasOwnProperty('NumeroDoc')) {
        obj['NumeroDoc'] = ApiClient.convertToType(data['NumeroDoc'], 'String');
      }
      if (data.hasOwnProperty('IdClub')) {
        obj['IdClub'] = ApiClient.convertToType(data['IdClub'], 'String');
      }
    }
    return obj;
  }

  /**
   * Inut type (0 for GovID 1 for Associate Number)
   * @member {String} TipoDato
   */
  exports.prototype['TipoDato'] = undefined;
  /**
   * User's ID card number or Associate Number
   * @member {String} NumeroDato
   */
  exports.prototype['NumeroDato'] = undefined;
  /**
   * User password
   * @member {String} ClaveSocio
   */
  exports.prototype['ClaveSocio'] = undefined;
  /**
   * @member {String} NumeroDoc
   */
  exports.prototype['NumeroDoc'] = undefined;
  /**
   * @member {String} IdClub
   */
  exports.prototype['IdClub'] = undefined;



  return exports;
}));


