/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.UserCheckResponse = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserCheckResponse model module.
   * @module model/UserCheckResponse
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>UserCheckResponse</code>.
   * @alias module:model/UserCheckResponse
   * @class
   * @param estado {String} value \"2\" if the user exists and has an email associated, value \"1\" if the user exists but does not have an email associated to him and \"0\" if the user does not exist.
   * @param frase {String} 
   */
  var exports = function(estado, frase) {
    var _this = this;

    _this['estado'] = estado;
    _this['frase'] = frase;
  };

  /**
   * Constructs a <code>UserCheckResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCheckResponse} obj Optional instance to populate.
   * @return {module:model/UserCheckResponse} The populated <code>UserCheckResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('estado')) {
        obj['estado'] = ApiClient.convertToType(data['estado'], 'String');
      }
      if (data.hasOwnProperty('frase')) {
        obj['frase'] = ApiClient.convertToType(data['frase'], 'String');
      }
    }
    return obj;
  }

  /**
   * value \"2\" if the user exists and has an email associated, value \"1\" if the user exists but does not have an email associated to him and \"0\" if the user does not exist.
   * @member {String} estado
   */
  exports.prototype['estado'] = undefined;
  /**
   * @member {String} frase
   */
  exports.prototype['frase'] = undefined;



  return exports;
}));


