/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Voucher = factory(root.LoyaltyProgramApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Voucher model module.
   * @module model/Voucher
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Voucher</code>.
   * @alias module:model/Voucher
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>Voucher</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Voucher} obj Optional instance to populate.
   * @return {module:model/Voucher} The populated <code>Voucher</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'String');
      }
      if (data.hasOwnProperty('fechaCarga')) {
        obj['fechaCarga'] = ApiClient.convertToType(data['fechaCarga'], 'String');
      }
      if (data.hasOwnProperty('fechaDesde')) {
        obj['fechaDesde'] = ApiClient.convertToType(data['fechaDesde'], 'String');
      }
      if (data.hasOwnProperty('fechaHasta')) {
        obj['fechaHasta'] = ApiClient.convertToType(data['fechaHasta'], 'String');
      }
      if (data.hasOwnProperty('titulo')) {
        obj['titulo'] = ApiClient.convertToType(data['titulo'], 'String');
      }
      if (data.hasOwnProperty('descripcion')) {
        obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
      }
      if (data.hasOwnProperty('visible')) {
        obj['visible'] = ApiClient.convertToType(data['visible'], 'String');
      }
      if (data.hasOwnProperty('basesYCondiciones')) {
        obj['basesYCondiciones'] = ApiClient.convertToType(data['basesYCondiciones'], 'String');
      }
      if (data.hasOwnProperty('fechaVencimientoCupon')) {
        obj['fechaVencimientoCupon'] = ApiClient.convertToType(data['fechaVencimientoCupon'], 'String');
      }
    }
    return obj;
  }

  /**
   * Voucher id
   * @member {String} pk
   */
  exports.prototype['pk'] = undefined;
  /**
   * Date when the voucher was created
   * @member {String} fechaCarga
   */
  exports.prototype['fechaCarga'] = undefined;
  /**
   * Date from when the voucher is available
   * @member {String} fechaDesde
   */
  exports.prototype['fechaDesde'] = undefined;
  /**
   * Date until when the voucher is available
   * @member {String} fechaHasta
   */
  exports.prototype['fechaHasta'] = undefined;
  /**
   * Voucher Title
   * @member {String} titulo
   */
  exports.prototype['titulo'] = undefined;
  /**
   * description
   * @member {String} descripcion
   */
  exports.prototype['descripcion'] = undefined;
  /**
   * Boolean defining if the voucher is visible
   * @member {String} visible
   */
  exports.prototype['visible'] = undefined;
  /**
   * Date Returned
   * @member {String} basesYCondiciones
   */
  exports.prototype['basesYCondiciones'] = undefined;
  /**
   * Date until when the voucher can be used
   * @member {String} fechaVencimientoCupon
   */
  exports.prototype['fechaVencimientoCupon'] = undefined;



  return exports;
}));


