/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Voucher'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Voucher'));
  } else {
    // Browser globals (root is window)
    if (!root.LoyaltyProgramApi) {
      root.LoyaltyProgramApi = {};
    }
    root.LoyaltyProgramApi.Vouchers = factory(root.LoyaltyProgramApi.ApiClient, root.LoyaltyProgramApi.Voucher);
  }
}(this, function(ApiClient, Voucher) {
  'use strict';




  /**
   * The Vouchers model module.
   * @module model/Vouchers
   * @version 4.0.2
   */

  /**
   * Constructs a new <code>Vouchers</code>.
   * @alias module:model/Vouchers
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Vouchers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vouchers} obj Optional instance to populate.
   * @return {module:model/Vouchers} The populated <code>Vouchers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Canjes')) {
        obj['Canjes'] = ApiClient.convertToType(data['Canjes'], [Voucher]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Voucher>} Canjes
   */
  exports.prototype['Canjes'] = undefined;



  return exports;
}));


