/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.CreditInstance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreditInstance', function() {
    it('should create an instance of CreditInstance', function() {
      // uncomment below and update the code to test CreditInstance
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be.a(LoyaltyProgramApi.CreditInstance);
    });

    it('should have the property pk (base name: "pk")', function() {
      // uncomment below and update the code to test the property pk
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property fkSocio (base name: "fk_socio")', function() {
      // uncomment below and update the code to test the property fkSocio
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property socio (base name: "socio")', function() {
      // uncomment below and update the code to test the property socio
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property fecha (base name: "fecha")', function() {
      // uncomment below and update the code to test the property fecha
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property concepto (base name: "concepto")', function() {
      // uncomment below and update the code to test the property concepto
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property fkTipoInstancia (base name: "fk_tipo_instancia")', function() {
      // uncomment below and update the code to test the property fkTipoInstancia
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property tipoInstancia (base name: "tipo_instancia")', function() {
      // uncomment below and update the code to test the property tipoInstancia
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property observaciones (base name: "observaciones")', function() {
      // uncomment below and update the code to test the property observaciones
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property fechaCarga (base name: "fechaCarga")', function() {
      // uncomment below and update the code to test the property fechaCarga
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property usuario (base name: "usuario")', function() {
      // uncomment below and update the code to test the property usuario
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property importe (base name: "importe")', function() {
      // uncomment below and update the code to test the property importe
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property fkCredito (base name: "fk_credito")', function() {
      // uncomment below and update the code to test the property fkCredito
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

    it('should have the property cuotasRestantes (base name: "cuotasRestantes")', function() {
      // uncomment below and update the code to test the property cuotasRestantes
      //var instane = new LoyaltyProgramApi.CreditInstance();
      //expect(instance).to.be();
    });

  });

}));
