/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.Prize();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Prize', function() {
    it('should create an instance of Prize', function() {
      // uncomment below and update the code to test Prize
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be.a(LoyaltyProgramApi.Prize);
    });

    it('should have the property pkPremio (base name: "pk_Premio")', function() {
      // uncomment below and update the code to test the property pkPremio
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property fkClubPropietario (base name: "fk_ClubPropietario")', function() {
      // uncomment below and update the code to test the property fkClubPropietario
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property fechaCarga (base name: "FechaCarga")', function() {
      // uncomment below and update the code to test the property fechaCarga
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property fechaDesde (base name: "FechaDesde")', function() {
      // uncomment below and update the code to test the property fechaDesde
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property fechaHasta (base name: "FechaHasta")', function() {
      // uncomment below and update the code to test the property fechaHasta
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property vencimientoCanje (base name: "VencimientoCanje")', function() {
      // uncomment below and update the code to test the property vencimientoCanje
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property cuentaRegresivaVisible (base name: "CuentaRegresivaVisible")', function() {
      // uncomment below and update the code to test the property cuentaRegresivaVisible
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property stock (base name: "Stock")', function() {
      // uncomment below and update the code to test the property stock
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property stockVisible (base name: "StockVisible")', function() {
      // uncomment below and update the code to test the property stockVisible
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property personasCanjesVisible (base name: "PersonasCanjesVisible")', function() {
      // uncomment below and update the code to test the property personasCanjesVisible
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property personasCanje (base name: "PersonasCanje")', function() {
      // uncomment below and update the code to test the property personasCanje
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property personasBaseCanje (base name: "PersonasBaseCanje")', function() {
      // uncomment below and update the code to test the property personasBaseCanje
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property titulo (base name: "Titulo")', function() {
      // uncomment below and update the code to test the property titulo
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property descripcion (base name: "Descripcion")', function() {
      // uncomment below and update the code to test the property descripcion
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property puntos (base name: "Puntos")', function() {
      // uncomment below and update the code to test the property puntos
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property masPuntos (base name: "MasPuntos")', function() {
      // uncomment below and update the code to test the property masPuntos
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property masPesos (base name: "MasPesos")', function() {
      // uncomment below and update the code to test the property masPesos
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property vigenteManual (base name: "VigenteManual")', function() {
      // uncomment below and update the code to test the property vigenteManual
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property fkUsuarioCarga (base name: "fk_UsuarioCarga")', function() {
      // uncomment below and update the code to test the property fkUsuarioCarga
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property nivelVisible (base name: "NivelVisible")', function() {
      // uncomment below and update the code to test the property nivelVisible
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property vigenteParaCampaniasInternas (base name: "VigenteParaCampaniasInternas")', function() {
      // uncomment below and update the code to test the property vigenteParaCampaniasInternas
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property comportamiento (base name: "Comportamiento")', function() {
      // uncomment below and update the code to test the property comportamiento
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property calificacionVisible (base name: "CalificacionVisible")', function() {
      // uncomment below and update the code to test the property calificacionVisible
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property calificacion (base name: "Calificacion")', function() {
      // uncomment below and update the code to test the property calificacion
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property palabrasClaves (base name: "PalabrasClaves")', function() {
      // uncomment below and update the code to test the property palabrasClaves
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property destacado (base name: "Destacado")', function() {
      // uncomment below and update the code to test the property destacado
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property visitas (base name: "Visitas")', function() {
      // uncomment below and update the code to test the property visitas
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property arrSucursales (base name: "ArrSucursales")', function() {
      // uncomment below and update the code to test the property arrSucursales
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property arrRubros (base name: "ArrRubros")', function() {
      // uncomment below and update the code to test the property arrRubros
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property arrTarjetas (base name: "ArrTarjetas")', function() {
      // uncomment below and update the code to test the property arrTarjetas
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property distancia (base name: "Distancia")', function() {
      // uncomment below and update the code to test the property distancia
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property descuento (base name: "Descuento")', function() {
      // uncomment below and update the code to test the property descuento
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property frase (base name: "Frase")', function() {
      // uncomment below and update the code to test the property frase
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property linkCorporativo (base name: "LinkCorporativo")', function() {
      // uncomment below and update the code to test the property linkCorporativo
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

    it('should have the property nombreBoton (base name: "NombreBoton")', function() {
      // uncomment below and update the code to test the property nombreBoton
      //var instane = new LoyaltyProgramApi.Prize();
      //expect(instance).to.be();
    });

  });

}));
