/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.Redemption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Redemption', function() {
    it('should create an instance of Redemption', function() {
      // uncomment below and update the code to test Redemption
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be.a(LoyaltyProgramApi.Redemption);
    });

    it('should have the property idCanje (base name: "IdCanje")', function() {
      // uncomment below and update the code to test the property idCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property idClubPremio (base name: "IdClubPremio")', function() {
      // uncomment below and update the code to test the property idClubPremio
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property idClubSocio (base name: "IdClubSocio")', function() {
      // uncomment below and update the code to test the property idClubSocio
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property idSocio (base name: "IdSocio")', function() {
      // uncomment below and update the code to test the property idSocio
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property idPremio (base name: "IdPremio")', function() {
      // uncomment below and update the code to test the property idPremio
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property fechaReserva (base name: "FechaReserva")', function() {
      // uncomment below and update the code to test the property fechaReserva
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property fechaCanjeado (base name: "FechaCanjeado")', function() {
      // uncomment below and update the code to test the property fechaCanjeado
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property fechaDevolucion (base name: "FechaDevolucion")', function() {
      // uncomment below and update the code to test the property fechaDevolucion
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property fechaVencimiento (base name: "FechaVencimiento")', function() {
      // uncomment below and update the code to test the property fechaVencimiento
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property usuarioReserva (base name: "UsuarioReserva")', function() {
      // uncomment below and update the code to test the property usuarioReserva
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property usuarioCanje (base name: "UsuarioCanje")', function() {
      // uncomment below and update the code to test the property usuarioCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property usuarioDevolucion (base name: "UsuarioDevolucion")', function() {
      // uncomment below and update the code to test the property usuarioDevolucion
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property sucursalReserva (base name: "SucursalReserva")', function() {
      // uncomment below and update the code to test the property sucursalReserva
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property sucursalCanje (base name: "SucursalCanje")', function() {
      // uncomment below and update the code to test the property sucursalCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property sucursalDevolucion (base name: "SucursalDevolucion")', function() {
      // uncomment below and update the code to test the property sucursalDevolucion
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property observaciones (base name: "Observaciones")', function() {
      // uncomment below and update the code to test the property observaciones
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property puntos (base name: "Puntos")', function() {
      // uncomment below and update the code to test the property puntos
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property pesos (base name: "Pesos")', function() {
      // uncomment below and update the code to test the property pesos
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property retiraEn (base name: "RetiraEn")', function() {
      // uncomment below and update the code to test the property retiraEn
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property codigoCanje (base name: "CodigoCanje")', function() {
      // uncomment below and update the code to test the property codigoCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property titulo (base name: "Titulo")', function() {
      // uncomment below and update the code to test the property titulo
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property nombreUsuarioReserva (base name: "NombreUsuarioReserva")', function() {
      // uncomment below and update the code to test the property nombreUsuarioReserva
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property nombreUsuarioCanje (base name: "NombreUsuarioCanje")', function() {
      // uncomment below and update the code to test the property nombreUsuarioCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property nombreUsuarioDevolucion (base name: "NombreUsuarioDevolucion")', function() {
      // uncomment below and update the code to test the property nombreUsuarioDevolucion
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property domicilioSucursalReserva (base name: "DomicilioSucursalReserva")', function() {
      // uncomment below and update the code to test the property domicilioSucursalReserva
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property domicilioSucursalCanje (base name: "DomicilioSucursalCanje")', function() {
      // uncomment below and update the code to test the property domicilioSucursalCanje
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property domicilioSucursalDevolucion (base name: "DomicilioSucursalDevolucion")', function() {
      // uncomment below and update the code to test the property domicilioSucursalDevolucion
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

    it('should have the property domicilioSucursalRetiraEn (base name: "DomicilioSucursalRetiraEn")', function() {
      // uncomment below and update the code to test the property domicilioSucursalRetiraEn
      //var instane = new LoyaltyProgramApi.Redemption();
      //expect(instance).to.be();
    });

  });

}));
