/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.SweepstakeDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SweepstakeDetails', function() {
    it('should create an instance of SweepstakeDetails', function() {
      // uncomment below and update the code to test SweepstakeDetails
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be.a(LoyaltyProgramApi.SweepstakeDetails);
    });

    it('should have the property nombreBoton (base name: "nombreBoton")', function() {
      // uncomment below and update the code to test the property nombreBoton
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property descripcionBoton (base name: "descripcionBoton")', function() {
      // uncomment below and update the code to test the property descripcionBoton
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property descripcion (base name: "descripcion")', function() {
      // uncomment below and update the code to test the property descripcion
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property basesYCondiciones (base name: "basesYCondiciones")', function() {
      // uncomment below and update the code to test the property basesYCondiciones
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property imagen (base name: "imagen")', function() {
      // uncomment below and update the code to test the property imagen
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property pk (base name: "pk")', function() {
      // uncomment below and update the code to test the property pk
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property nombre (base name: "nombre")', function() {
      // uncomment below and update the code to test the property nombre
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property fechaDesde (base name: "fechaDesde")', function() {
      // uncomment below and update the code to test the property fechaDesde
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property fechaHasta (base name: "fechaHasta")', function() {
      // uncomment below and update the code to test the property fechaHasta
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

    it('should have the property estado (base name: "estado")', function() {
      // uncomment below and update the code to test the property estado
      //var instane = new LoyaltyProgramApi.SweepstakeDetails();
      //expect(instance).to.be();
    });

  });

}));
