/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.Ticket();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Ticket', function() {
    it('should create an instance of Ticket', function() {
      // uncomment below and update the code to test Ticket
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be.a(LoyaltyProgramApi.Ticket);
    });

    it('should have the property idMovimiento (base name: "IdMovimiento")', function() {
      // uncomment below and update the code to test the property idMovimiento
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property descripcionSucursal (base name: "DescripcionSucursal")', function() {
      // uncomment below and update the code to test the property descripcionSucursal
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property usuario (base name: "Usuario")', function() {
      // uncomment below and update the code to test the property usuario
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property fecha (base name: "Fecha")', function() {
      // uncomment below and update the code to test the property fecha
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property hora (base name: "Hora")', function() {
      // uncomment below and update the code to test the property hora
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property movimiento (base name: "Movimiento")', function() {
      // uncomment below and update the code to test the property movimiento
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property ticket (base name: "Ticket")', function() {
      // uncomment below and update the code to test the property ticket
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property importeCompra (base name: "ImporteCompra")', function() {
      // uncomment below and update the code to test the property importeCompra
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property puntosCarga (base name: "PuntosCarga")', function() {
      // uncomment below and update the code to test the property puntosCarga
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property puntosAntesCarga (base name: "PuntosAntesCarga")', function() {
      // uncomment below and update the code to test the property puntosAntesCarga
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property puntosDespuesCarga (base name: "PuntosDespuesCarga")', function() {
      // uncomment below and update the code to test the property puntosDespuesCarga
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property detalle (base name: "Detalle")', function() {
      // uncomment below and update the code to test the property detalle
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property anulado (base name: "Anulado")', function() {
      // uncomment below and update the code to test the property anulado
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

    it('should have the property usuarioAnula (base name: "UsuarioAnula")', function() {
      // uncomment below and update the code to test the property usuarioAnula
      //var instane = new LoyaltyProgramApi.Ticket();
      //expect(instance).to.be();
    });

  });

}));
