/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.UserInformation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserInformation', function() {
    it('should create an instance of UserInformation', function() {
      // uncomment below and update the code to test UserInformation
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be.a(LoyaltyProgramApi.UserInformation);
    });

    it('should have the property mClave (base name: "mClave")', function() {
      // uncomment below and update the code to test the property mClave
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mCodigoPostal (base name: "mCodigoPostal")', function() {
      // uncomment below and update the code to test the property mCodigoPostal
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mOrigenDelAlta (base name: "mOrigenDelAlta")', function() {
      // uncomment below and update the code to test the property mOrigenDelAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mNdeCliente (base name: "mNdeCliente")', function() {
      // uncomment below and update the code to test the property mNdeCliente
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mUsuarioAlta (base name: "mUsuarioAlta")', function() {
      // uncomment below and update the code to test the property mUsuarioAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mId (base name: "mId")', function() {
      // uncomment below and update the code to test the property mId
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mIdClub (base name: "mIdClub")', function() {
      // uncomment below and update the code to test the property mIdClub
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mApellido (base name: "mApellido")', function() {
      // uncomment below and update the code to test the property mApellido
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mNombre (base name: "mNombre")', function() {
      // uncomment below and update the code to test the property mNombre
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mGenero (base name: "mGenero")', function() {
      // uncomment below and update the code to test the property mGenero
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mIdTipoDoc (base name: "mIdTipoDoc")', function() {
      // uncomment below and update the code to test the property mIdTipoDoc
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mTipoDocumento (base name: "mTipoDocumento")', function() {
      // uncomment below and update the code to test the property mTipoDocumento
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mNumeroDoc (base name: "mNumeroDoc")', function() {
      // uncomment below and update the code to test the property mNumeroDoc
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mMail (base name: "mMail")', function() {
      // uncomment below and update the code to test the property mMail
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mFechaAlta (base name: "mFechaAlta")', function() {
      // uncomment below and update the code to test the property mFechaAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mFechaNac (base name: "mFechaNac")', function() {
      // uncomment below and update the code to test the property mFechaNac
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mTelefono (base name: "mTelefono")', function() {
      // uncomment below and update the code to test the property mTelefono
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mCelular (base name: "mCelular")', function() {
      // uncomment below and update the code to test the property mCelular
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mDireccion (base name: "mDireccion")', function() {
      // uncomment below and update the code to test the property mDireccion
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mFkCiudad (base name: "mFk_Ciudad")', function() {
      // uncomment below and update the code to test the property mFkCiudad
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mLocalidad (base name: "mLocalidad")', function() {
      // uncomment below and update the code to test the property mLocalidad
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mNumeroTarjeta (base name: "mNumeroTarjeta")', function() {
      // uncomment below and update the code to test the property mNumeroTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mIdTipoTarjeta (base name: "mIdTipoTarjeta")', function() {
      // uncomment below and update the code to test the property mIdTipoTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mTipoTarjeta (base name: "mTipoTarjeta")', function() {
      // uncomment below and update the code to test the property mTipoTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mPuntosAcumuladosClub (base name: "mPuntosAcumuladosClub")', function() {
      // uncomment below and update the code to test the property mPuntosAcumuladosClub
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mImagenPerfil (base name: "mImagenPerfil")', function() {
      // uncomment below and update the code to test the property mImagenPerfil
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property idClub (base name: "IdClub")', function() {
      // uncomment below and update the code to test the property idClub
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property idSocio (base name: "IdSocio")', function() {
      // uncomment below and update the code to test the property idSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property apellidoSocio (base name: "ApellidoSocio")', function() {
      // uncomment below and update the code to test the property apellidoSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property nombreSocio (base name: "NombreSocio")', function() {
      // uncomment below and update the code to test the property nombreSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property sexo (base name: "Sexo")', function() {
      // uncomment below and update the code to test the property sexo
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property idTipoDocumento (base name: "IdTipoDocumento")', function() {
      // uncomment below and update the code to test the property idTipoDocumento
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property numeroDoc (base name: "NumeroDoc")', function() {
      // uncomment below and update the code to test the property numeroDoc
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property mailSocio (base name: "MailSocio")', function() {
      // uncomment below and update the code to test the property mailSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property fechaNacimiento (base name: "FechaNacimiento")', function() {
      // uncomment below and update the code to test the property fechaNacimiento
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property telefonoSocio (base name: "TelefonoSocio")', function() {
      // uncomment below and update the code to test the property telefonoSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property celularSocio (base name: "CelularSocio")', function() {
      // uncomment below and update the code to test the property celularSocio
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property direccion (base name: "Direccion")', function() {
      // uncomment below and update the code to test the property direccion
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property fkCiudad (base name: "fk_Ciudad")', function() {
      // uncomment below and update the code to test the property fkCiudad
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property idTipoTarjeta (base name: "IdTipoTarjeta")', function() {
      // uncomment below and update the code to test the property idTipoTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property clave (base name: "Clave")', function() {
      // uncomment below and update the code to test the property clave
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property codigoPostal (base name: "CodigoPostal")', function() {
      // uncomment below and update the code to test the property codigoPostal
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property origenDelAlta (base name: "OrigenDelAlta")', function() {
      // uncomment below and update the code to test the property origenDelAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property nDeCliente (base name: "NDeCliente")', function() {
      // uncomment below and update the code to test the property nDeCliente
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property usuarioAlta (base name: "UsuarioAlta")', function() {
      // uncomment below and update the code to test the property usuarioAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property ocupacion (base name: "Ocupacion")', function() {
      // uncomment below and update the code to test the property ocupacion
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property localidad (base name: "Localidad")', function() {
      // uncomment below and update the code to test the property localidad
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property numeroTarjeta (base name: "NumeroTarjeta")', function() {
      // uncomment below and update the code to test the property numeroTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property puntosAcumuladosClub (base name: "PuntosAcumuladosClub")', function() {
      // uncomment below and update the code to test the property puntosAcumuladosClub
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property tipoDocumento (base name: "TipoDocumento")', function() {
      // uncomment below and update the code to test the property tipoDocumento
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property fechaAlta (base name: "FechaAlta")', function() {
      // uncomment below and update the code to test the property fechaAlta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property tipoDeTarjeta (base name: "TipoDeTarjeta")', function() {
      // uncomment below and update the code to test the property tipoDeTarjeta
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

    it('should have the property imagenPerfil (base name: "ImagenPerfil")', function() {
      // uncomment below and update the code to test the property imagenPerfil
      //var instane = new LoyaltyProgramApi.UserInformation();
      //expect(instance).to.be();
    });

  });

}));
