/**
 * Loyalty Program API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0.2
 * Contact: eduardo@linead.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.16
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoyaltyProgramApi);
  }
}(this, function(expect, LoyaltyProgramApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoyaltyProgramApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be.a(LoyaltyProgramApi.User);
    });

    it('should have the property idClub (base name: "IdClub")', function() {
      // uncomment below and update the code to test the property idClub
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property idSocio (base name: "IdSocio")', function() {
      // uncomment below and update the code to test the property idSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property apellidoSocio (base name: "ApellidoSocio")', function() {
      // uncomment below and update the code to test the property apellidoSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property nombreSocio (base name: "NombreSocio")', function() {
      // uncomment below and update the code to test the property nombreSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property sexo (base name: "Sexo")', function() {
      // uncomment below and update the code to test the property sexo
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property idTipoDoc (base name: "IdTipoDoc")', function() {
      // uncomment below and update the code to test the property idTipoDoc
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property tipoDocumento (base name: "TipoDocumento")', function() {
      // uncomment below and update the code to test the property tipoDocumento
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property numeroDoc (base name: "NumeroDoc")', function() {
      // uncomment below and update the code to test the property numeroDoc
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property mailSocio (base name: "MailSocio")', function() {
      // uncomment below and update the code to test the property mailSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property fechaAlta (base name: "FechaAlta")', function() {
      // uncomment below and update the code to test the property fechaAlta
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property fechaNacimiento (base name: "FechaNacimiento")', function() {
      // uncomment below and update the code to test the property fechaNacimiento
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property telefonoSocio (base name: "TelefonoSocio")', function() {
      // uncomment below and update the code to test the property telefonoSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property celularSocio (base name: "CelularSocio")', function() {
      // uncomment below and update the code to test the property celularSocio
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property direccion (base name: "Direccion")', function() {
      // uncomment below and update the code to test the property direccion
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property fkCiudad (base name: "fk_Ciudad")', function() {
      // uncomment below and update the code to test the property fkCiudad
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property localidad (base name: "Localidad")', function() {
      // uncomment below and update the code to test the property localidad
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property numeroTarjeta (base name: "NumeroTarjeta")', function() {
      // uncomment below and update the code to test the property numeroTarjeta
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property idTipoTarjeta (base name: "IdTipoTarjeta")', function() {
      // uncomment below and update the code to test the property idTipoTarjeta
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property tipoDeTarjeta (base name: "TipoDeTarjeta")', function() {
      // uncomment below and update the code to test the property tipoDeTarjeta
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property puntosAcumuladosClub (base name: "PuntosAcumuladosClub")', function() {
      // uncomment below and update the code to test the property puntosAcumuladosClub
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property imagenPerfil (base name: "ImagenPerfil")', function() {
      // uncomment below and update the code to test the property imagenPerfil
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

    it('should have the property ocupacion (base name: "Ocupacion")', function() {
      // uncomment below and update the code to test the property ocupacion
      //var instane = new LoyaltyProgramApi.User();
      //expect(instance).to.be();
    });

  });

}));
